"""Outbound ports — what the domain core needs from the outside world.

Adapters implement these. The core never imports an adapter.
"""
from __future__ import annotations

from typing import Protocol

from app.domain.user import User


class DatabaseProbe(Protocol):
    def check(self) -> tuple[bool, str]:
        """Return (reachable, detail). Must never raise."""
        ...


class UserRepository(Protocol):
    def save(self, user: User) -> None: ...
    def find_by_email(self, email: str) -> User | None: ...
    def get(self, user_id: str) -> User | None: ...
    def update_role(self, user_id: str, role: str) -> User | None: ...
    def delete(self, user_id: str) -> None: ...


class PasswordHasher(Protocol):
    def hash(self, password: str) -> str: ...
    def verify(self, password: str, password_hash: str) -> bool: ...


class TokenIssuer(Protocol):
    def issue_access(self, user: User) -> str: ...
    def issue_refresh(self, user: User) -> str: ...
    def decode(self, token: str) -> dict:
        """Return claims. Raises DomainError on invalid/expired token."""
        ...


class TokenStore(Protocol):
    def store(self, token: str, user_id: str, expires_at: object) -> None: ...
    def revoke(self, token: str) -> None: ...
    def is_revoked(self, token: str) -> bool: ...
    def owner_of(self, token: str) -> str | None: ...
    def revoke_all_for_user(self, user_id: str) -> None: ...


class ProfileRepository(Protocol):
    def save(self, profile: object) -> None: ...
    def get_by_user(self, user_id: str) -> object | None: ...


class PlacementRepository(Protocol):
    def save(self, placement: object) -> None: ...
    def get(self, placement_id: str) -> object | None: ...


class AssessmentRepository(Protocol):
    def save(self, assessment: object) -> None: ...
    def get(self, assessment_id: str) -> object | None: ...
    def list_for_user(self, user_id: str) -> list[object]: ...


class QuestionBank(Protocol):
    def topics(self) -> list[str]: ...
    def questions(self, topic: str, level: str, count: int) -> list[object]: ...
    def get(self, question_id: str) -> object | None: ...


class OAuthProvider(Protocol):
    def auth_url(self, state: str) -> str:
        """Return the provider authorization URL. Raises DomainError if unconfigured."""
        ...

    def exchange(self, code: str) -> str:
        """Exchange an auth code for the user's email. Raises DomainError on failure."""
        ...
